<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="57493" started-at="2020-05-11T12:17:57 BST" finished-at="2020-05-11T12:18:55 BST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="57493" started-at="2020-05-11T12:17:57 BST" finished-at="2020-05-11T12:18:55 BST">
      <class name="com.core.ddf.testcases.LoginTest">
        <test-method status="PASS" signature="start()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="start" is-config="true" duration-ms="15" started-at="2020-05-11T12:17:58 BST" finished-at="2020-05-11T12:17:58 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="loginTest" duration-ms="63" started-at="2020-05-11T12:17:58 BST" data-provider="getdata" finished-at="2020-05-11T12:17:58 BST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PassWord=P1, ExpectedResult=Fail, RunMode=N, UserName=U1, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[TestCase Skipped as RunMode is N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: TestCase Skipped as RunMode is N
at com.core.ddf.util.DataUtil.checkTestCasesRunmode(DataUtil.java:108)
at com.core.ddf.testcases.LoginTest.loginTest(LoginTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="quit" is-config="true" duration-ms="316" started-at="2020-05-11T12:17:58 BST" finished-at="2020-05-11T12:17:58 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="start()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="start" is-config="true" duration-ms="1" started-at="2020-05-11T12:17:58 BST" finished-at="2020-05-11T12:17:58 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="loginTest" duration-ms="37389" started-at="2020-05-11T12:17:58 BST" data-provider="getdata" finished-at="2020-05-11T12:18:36 BST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PassWord=P2, ExpectedResult=Fail, RunMode=Y, UserName=swinal01_10@yahoo.co.in, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Username and password does not match. Try again.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Username and password does not match. Try again.
at org.testng.Assert.fail(Assert.java:97)
at com.core.ddf.base.BaseTest.reportFailure(BaseTest.java:253)
at com.core.ddf.base.BaseTest.doLogin(BaseTest.java:128)
at com.core.ddf.testcases.LoginTest.loginTest(LoginTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="quit" is-config="true" duration-ms="741" started-at="2020-05-11T12:18:36 BST" finished-at="2020-05-11T12:18:36 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="start()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="start" is-config="true" duration-ms="0" started-at="2020-05-11T12:18:36 BST" finished-at="2020-05-11T12:18:36 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="loginTest" duration-ms="47" started-at="2020-05-11T12:18:36 BST" data-provider="getdata" finished-at="2020-05-11T12:18:36 BST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PassWord=Patel888!, ExpectedResult=Fail, RunMode=N, UserName=U3, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[TestCase Skipped as RunMode is N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: TestCase Skipped as RunMode is N
at com.core.ddf.util.DataUtil.checkTestCasesRunmode(DataUtil.java:108)
at com.core.ddf.testcases.LoginTest.loginTest(LoginTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="quit" is-config="true" duration-ms="15" started-at="2020-05-11T12:18:36 BST" finished-at="2020-05-11T12:18:36 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="loginTest" duration-ms="15998" started-at="2020-05-11T12:18:36 BST" data-provider="getdata" finished-at="2020-05-11T12:18:52 BST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PassWord=Patel888!, ExpectedResult=Pass, RunMode=Y, UserName=swinal01_10@yahoo.co.in, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="start()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="start" is-config="true" duration-ms="0" started-at="2020-05-11T12:18:36 BST" finished-at="2020-05-11T12:18:36 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="quit" is-config="true" duration-ms="2307" started-at="2020-05-11T12:18:52 BST" finished-at="2020-05-11T12:18:55 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="start()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="start" is-config="true" duration-ms="0" started-at="2020-05-11T12:18:55 BST" finished-at="2020-05-11T12:18:55 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="loginTest" duration-ms="39" started-at="2020-05-11T12:18:55 BST" data-provider="getdata" finished-at="2020-05-11T12:18:55 BST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PassWord=P5, ExpectedResult=Fail, RunMode=N, UserName=U5, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[TestCase Skipped as RunMode is N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: TestCase Skipped as RunMode is N
at com.core.ddf.util.DataUtil.checkTestCasesRunmode(DataUtil.java:108)
at com.core.ddf.testcases.LoginTest.loginTest(LoginTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.core.ddf.testcases.LoginTest@429bd883]" name="quit" is-config="true" duration-ms="14" started-at="2020-05-11T12:18:55 BST" finished-at="2020-05-11T12:18:55 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.core.ddf.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
